export default [
    {
        name:             'x-lights',
        '--primary':      '#00ffff',
        '--primary-dark': '#005555',
        '--secondary':    '#ffff00',
        '--bg':           '#161616',
        '--bg-rgb':       '22,22,22',
        '--bg-contrast':  '#222222',
        '--bg-light':     '#292929',
        '--bg-lighter':   '#555',
        '--font':         '#fff',
        '--grey':         '#ddd',
        '--black':        '#000',
        '--white':        '#fff',
        '--red':          '#f55',
    },
    {
        name:             'x-lights-light',
        '--primary':      '#7700aa',
        '--primary-dark': '#7700aa',
        '--secondary':    '#00dd88',
        '--bg':           '#bbb',
        '--bg-rgb':       '187,187,187',
        '--bg-contrast':  '#ccc',
        '--bg-light':     '#b2b2b2',
        '--bg-lighter':   '#949494',
        '--font':         '#333',
        '--grey':         '#ddd',
        '--black':        '#000',
        '--white':        '#fff',
        '--red':          '#f55',
    }
];
